{% set name = "genai" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/genai-{{ version }}.tar.gz
  sha256: 96defbf72e08f20e3b756f9cf337a58667edfe0d9a1be8fcad01efce93d7efca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.1
  run:
    - python >={{ python_min }}
    - openai >=0.27.0
    - vdom >=0.6
    - ipython >=8.10.0
    - tabulate >=0.9.0
    - tiktoken >=0.3.2


test:
  imports:
    - genai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Generative AI for IPython (enhance your code cells)
  description: |
    Generative AI tooling for IPython using OpenAI's API.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/noteable-io/genai
  doc_url: https://github.com/noteable-io/genai
  dev_url: https://github.com/noteable-io/genai



extra:
  recipe-maintainers:
    - andersy005
